/**
 * Tuner — persistence layer.
 *
 * Atomic JSON / TypeScript-snippet writes (write-temp + rename, so a kill
 * mid-write never produces a corrupt file), append-only progress log, and a
 * resume-from-disk loader that lets `--mode=overnight` pick up where a prior
 * run left off.
 */

import {
  existsSync,
  mkdirSync,
  readFileSync,
  renameSync,
  writeFileSync,
  appendFileSync,
} from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { DEFAULT_V7_PARAMS, type V7Params } from '../../src/prusa-fdm-mixer.js';
import { PARAM_KEYS } from './params.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

/** Default output directory: apps/tuner/output. */
export const DEFAULT_OUTPUT_DIR = resolve(__dirname, 'output');

/** Ensure the output directory exists. */
export function ensureOutputDir(dir: string = DEFAULT_OUTPUT_DIR): void {
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
}

// ---------------------------------------------------------------------------
// Atomic file writes
// ---------------------------------------------------------------------------

/**
 * Write `content` to `path` atomically: write to `path.tmp`, then rename.
 * `renameSync` is atomic on POSIX, so the destination either has the old
 * bytes or the new bytes — never partial.
 */
export function atomicWriteFile(path: string, content: string): void {
  const tmp = path + '.tmp';
  writeFileSync(tmp, content, 'utf8');
  renameSync(tmp, path);
}

// ---------------------------------------------------------------------------
// V7Params <-> JSON
// ---------------------------------------------------------------------------

export interface PersistedParams {
  /** ISO 8601 timestamp of the write. */
  timestamp: string;
  /** Iteration index at write time (0 = the initial default). */
  iteration: number;
  /** Mean ΔE2000 on the training set (all 122 mixes) with these params. */
  trainMeanDE: number;
  /** Mean ΔE2000 under LOFO-CV held-out, if known; else null. */
  lofoMeanDE: number | null;
  /** Mean ΔE2000 on Lipstick-Red held-out, if known; else null. */
  lipstickHeldOutDE: number | null;
  /** The tuned params themselves. */
  params: V7Params;
  /** Optional human-readable note (e.g., "from coordinate descent restart"). */
  note?: string;
}

export function writePersistedJson(path: string, p: PersistedParams): void {
  atomicWriteFile(path, JSON.stringify(p, null, 2) + '\n');
}

export function readPersistedJson(path: string): PersistedParams | null {
  if (!existsSync(path)) return null;
  try {
    const text = readFileSync(path, 'utf8');
    return JSON.parse(text) as PersistedParams;
  } catch {
    return null;
  }
}

// ---------------------------------------------------------------------------
// V7Params -> TypeScript snippet
// ---------------------------------------------------------------------------

/** Format a number for the TS snippet: 6 sig figs, no trailing zeros. */
function fmtNum(x: number): string {
  if (!isFinite(x)) return String(x);
  // Round to 6 significant figures, then strip trailing zeros.
  const s = x.toPrecision(6);
  // Avoid scientific notation when not needed.
  if (s.includes('e') || s.includes('E')) return s;
  return parseFloat(s).toString();
}

/** Build a copy-pasteable `DEFAULT_V7_PARAMS` snippet with a metric-rich header. */
export function formatTsSnippet(p: PersistedParams): string {
  const lines: string[] = [];
  lines.push('// Generated by apps/tuner @ ' + p.timestamp + ', iter ' + p.iteration);
  lines.push('// Training mean ΔE: ' + fmtNum(p.trainMeanDE));
  if (p.lofoMeanDE !== null) {
    lines.push('// LOFO-CV mean ΔE: ' + fmtNum(p.lofoMeanDE));
  }
  if (p.lipstickHeldOutDE !== null) {
    lines.push('// Lipstick-held-out mean ΔE: ' + fmtNum(p.lipstickHeldOutDE));
  }
  if (p.note) lines.push('// Note: ' + p.note);
  lines.push('');
  lines.push('export const DEFAULT_V7_PARAMS: V7Params = {');
  for (const k of PARAM_KEYS) {
    lines.push('  ' + k + ': ' + fmtNum(p.params[k]) + ',');
  }
  lines.push('};');
  lines.push('');
  return lines.join('\n');
}

export function writeTsSnippet(path: string, p: PersistedParams): void {
  atomicWriteFile(path, formatTsSnippet(p));
}

// ---------------------------------------------------------------------------
// Bundle: write JSON + TS together
// ---------------------------------------------------------------------------

export interface BundlePaths {
  json: string;
  ts: string;
}

export function bundlePaths(outputDir: string, prefix: string): BundlePaths {
  return {
    json: join(outputDir, prefix + '-params.json'),
    ts: join(outputDir, prefix + '-params.ts'),
  };
}

export function writeBundle(paths: BundlePaths, p: PersistedParams): void {
  writePersistedJson(paths.json, p);
  writeTsSnippet(paths.ts, p);
}

// ---------------------------------------------------------------------------
// Append-only progress log
// ---------------------------------------------------------------------------

export interface ProgressEntry {
  timestamp: string;
  iteration: number;
  optimizer: string;
  trainMeanDE: number;
  lofoMeanDE: number | null;
  lipstickHeldOutDE: number | null;
  evaluations: number;
}

/** Append a single progress line as JSON Lines. */
export function appendProgress(path: string, e: ProgressEntry): void {
  appendFileSync(path, JSON.stringify(e) + '\n', 'utf8');
}

// ---------------------------------------------------------------------------
// Resume
// ---------------------------------------------------------------------------

/**
 * Look for a previous best-train file. If found, return its params as a
 * starting seed for the current run. Otherwise return DEFAULT_V7_PARAMS.
 */
export function resumeOrDefault(outputDir: string = DEFAULT_OUTPUT_DIR): {
  params: V7Params;
  resumed: boolean;
  meta: PersistedParams | null;
} {
  const path = join(outputDir, 'best-train-params.json');
  const meta = readPersistedJson(path);
  if (meta) return { params: meta.params, resumed: true, meta };
  return { params: DEFAULT_V7_PARAMS, resumed: false, meta: null };
}

// ---------------------------------------------------------------------------
// Signal handling
// ---------------------------------------------------------------------------

/**
 * Install SIGINT / SIGTERM handlers that flip a flag and call `onShutdown`.
 * The runner polls the flag in its outer loop and exits cleanly. Returns
 * the flag-getter so callers can poll.
 */
export function installShutdownHandler(onShutdown?: () => void): () => boolean {
  let shutdown = false;
  const handler = () => {
    if (shutdown) return; // re-entrant safety
    shutdown = true;
    if (onShutdown) {
      try {
        onShutdown();
      } catch {
        // Swallow — the flag is already set; the runner will exit on its own.
      }
    }
  };
  process.on('SIGINT', handler);
  process.on('SIGTERM', handler);
  return () => shutdown;
}
